# Form implementation generated from reading ui file 'c:\Users\Ali.Khdour\Desktop\TestQT\SearchScreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(396, 317)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(313, 5, 81, 21))
        self.SearchButton.setObjectName("SearchButton")
        self.TeamInfoLog = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.TeamInfoLog.setGeometry(QtCore.QRect(13, 36, 381, 241))
        self.TeamInfoLog.setObjectName("TeamInfoLog")
        self.SearchBar = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(13, 5, 291, 21))
        self.SearchBar.setObjectName("SearchBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
